### ISSUE TITLE
Durationtimer for Grid2 (de)buffs

### ISSUE THREAD

**Issue by skmzarn** [tullamods/tullaCC#15]
Hi. I can't get the duration timer to work from Grid2's buffs/debuffs with TullaCC.

It does work with OmniCC, but I do like TullaCC better, and want it to work with it as well. Can you please check this? Thank you.

**Comment by Tuller** [comment]
In general I need to port the engine back from omnicc

**Comment by skmzarn** [comment]
Okay, is that something you are going to do in the future? I mean, if you can still keep tullaCC on low cpu even with this feature. I like the simplicity with tullaCC.

**Comment by Tuller** [comment]
OmniCC’s latest iteration is s bit more optimized than tullaCC. I actually started it’s latest version via porting over the optimizations from tullaCC, but then made a bunch of optimizations I now need to port back.

**Comment by skmzarn** [comment]
Okay, so are you going to focus on to get OmniCC better optimized? I think that would be the best since it has very friendly configs and more features for everyone.

**Comment by Tuller** [comment]
I will likely backport the changes from OmniCC to tullaCC since it is better optimized at the moment.

**Comment by skmzarn** [comment]
Okay, cool. Thanks for doing this.

**Comment by Tuller** [comment]
I actually got around to doing this https://github.com/tullamods/tullaCC/releases/latest

**Comment by skmzarn** [comment]
Thank you for this. I am currently testing it, and it seems to be working. :)
