### ISSUE TITLE
TullaCC acting like omniCC

### ISSUE THREAD

**Issue by Camphund** [tullamods/tullaCC#16]
hey im not a programer what so ever but i have noticed sence yesterday or early today that tullaCC have been acting like omniCC in the manner of that i can still see a countdown on enemy debuffs it occures on both classic wow and retail wow. I noticed when i last updated the addon and i would love if tullaCC to work like it used to thanks in advance and keep up the good job.

**Comment by Tuller** [comment]
Looks like I forgot to change a variable name. Try with 8.2.1.

**Comment by Camphund** [comment]
seems to be working fine thanks !

**Comment by Camphund** [comment]
i noticed today on retail that the countdown is still on nameplate debuffs

**Comment by Camphund** [comment]
and if im not misstaken cooldown numbers are slightly faded and looks abit weard especaly on longer cds like toys that have 24h cd and so on

**Comment by Tuller** [comment]
Try the beta, where I've adjusted the cooldown colors a bit.
https://github.com/tullamods/tullaCC/releases/tag/8.2.2-beta

You can then adjust the scale a bit easier via
```lua
/run tullaCC.Config.minScale = 0.8; ReloadUI()
```
