### ISSUE TITLE
LUA error, breaks the addon

### ISSUE THREAD

**Issue by skmzarn** [tullamods/tullaCC#18]
The LUA error below breaks the addon completely. It happened immediately after I joined a group, and a reload UI didn't work. All of a sudden sometime in the middle of the Mythic+ dungeon, the timers worked again.

> `4084x tullaCC\cooldown.lua:126: attempt to index local 'style' (a nil value)
> tullaCC\cooldown.lua:126: in function `UpdateStyle'
> tullaCC\cooldown.lua:152: in function <tullaCC\cooldown.lua:149>
> 
> Locals:
> self = Grid2iconbuffs0105 {
>  0 = <userdata>
>  _tcc_start = 0
>  _tcc_duration = 0
> }
> style = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "attempt to index local 'style' (a nil value)"
> Addon = <table> {
>  PLAYER_LOGOUT = <function> defined @tullaCC\main.lua:33
>  CleanupDatabase = <function> defined @tullaCC\config.lua:47
>  eventHandler = <unnamed> {
>  }
>  SetupDatabase = <function> defined @tullaCC\config.lua:33
>  Config = <table> {
>  }
>  ResetDatabase = <function> defined @tullaCC\config.lua:188
>  PLAYER_LOGIN = <function> defined @tullaCC\main.lua:28
>  OnEvent = <function> defined @tullaCC\main.lua:21
>  Timer = <table> {
>  }
>  Display = <unnamed> {
>  }
>  Cooldown = <table> {
>  }
>  GetDatabaseDefaults = <function> defined @tullaCC\config.lua:54
> }
> `

**Comment by Tuller** [comment]
This should be fixed in 8.2.2 (release)
